/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prepus;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class daftarpeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form daftarpeminjaman
     */
    private Connection koneksi;
    koneksi db = new koneksi();
    public daftarpeminjaman() {
        initComponents();
        jLabel1.setText(main.getnama());
        jLabel2.setText(""+main.getid_user());
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        idmember.setVisible(false);
        loadtbl();
    }
    private void loadtbl(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addColumn("Kode Buku");
        model.addColumn("Judul");
        model.addColumn("ID Member");
        model.addColumn("Nama Member");
        model.addColumn("Tanggal Dipinjam");
        model.addColumn("Tanggal Kembali");
        model.addColumn("Status Buku");
        model.addColumn("Banyak Buku yang dipinjam");
        model.addColumn("ID User");
        model.addColumn("Operator");


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kode = new javax.swing.JTextField();
        judul = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pengarang = new javax.swing.JTextField();
        lokasirak = new javax.swing.JTextField();
        jumlahhalaman = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        tahunterbit = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        namamember = new javax.swing.JTextField();
        tglpinjam = new javax.swing.JTextField();
        tglkembali = new javax.swing.JTextField();
        banyak = new javax.swing.JTextField();
        idmember = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kode.setBorder(null);
        getContentPane().add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 240, 30));

        judul.setEditable(false);
        judul.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        judul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 315, 320, 45));

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 750, 280));

        pengarang.setEditable(false);
        pengarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pengarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 376, 320, 45));

        lokasirak.setEditable(false);
        lokasirak.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lokasirak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lokasirak, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 625, 320, 45));

        jumlahhalaman.setEditable(false);
        jumlahhalaman.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahhalaman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jumlahhalaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 562, 320, 45));

        penerbit.setEditable(false);
        penerbit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        penerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 435, 320, 45));

        tahunterbit.setEditable(false);
        tahunterbit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tahunterbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tahunterbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 320, 45));

        stok.setEditable(false);
        stok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 685, 320, 45));

        nama.setBorder(null);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 192, 205, 35));

        namamember.setEditable(false);
        namamember.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        namamember.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(namamember, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 290, 45));

        tglpinjam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tglpinjam.setText("YYYYMMDD");
        tglpinjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tglpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 290, 45));

        tglkembali.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tglkembali.setText("YYYYMMDD");
        tglkembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tglkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 290, 45));

        banyak.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        banyak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(banyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 252, 320, 45));

        idmember.setBorder(null);
        getContentPane().add(idmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 170, -1));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 310, 50));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tambahkan");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 270, 30));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 270, 80, 80));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 180, 100, 80));

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 360, 160, 80));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 190, 60, 40));

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 70, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/List peminjaman (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new listpeminjam().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        member m = new member();
        buku b = new buku();
        pinjam p = new pinjam();
        
        String jb = judul.getText();
        String im = idmember.getText();
        String nm = namamember.getText();
        String ps = tglpinjam.getText();
        String pk = tglkembali.getText();
        
        String status = m.STATUS()+"berhasil ditambahkan";
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int reply = JOptionPane.showConfirmDialog(null, "Apakah data sudah sesuai?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try{
                String sql = "Update buku set stok = '"+stok.getText()+"' - '"+banyak.getText()+"' "
                + "where judul = '"+jb+"'";
                PreparedStatement prp = db.getConnection().prepareStatement(sql);
                prp.executeUpdate();
            }
            catch(SQLException e ){

            }
            JOptionPane.showMessageDialog(null, status);
            String statusbuku = "Belum dikembalikan ";
            model.addRow(new Object[]{kode.getText(),
                jb,
                im,
                nm,
                ps,
                pk,
                statusbuku,
                Integer.parseInt(banyak.getText()),
                jLabel2.getText(),
                jLabel1.getText()});
        }
        else {
            JOptionPane.showMessageDialog(null, "oke");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        try{
            db.koneksiDB();
            buku b = new buku();
            int rows = jTable1.getRowCount();
            PreparedStatement pst;
            PreparedStatement psp;
            for (int row = 0; row < rows; row++) {
                String judul = (String) jTable1.getValueAt(row, 1);
                String setstok = "select * from buku where judul = '"+judul+"'";
                psp = db.getConnection().prepareStatement(setstok);
                ResultSet res = psp.executeQuery();
                while (res.next()){
                    int stok = res.getInt(7);
                    int banyak = (int) jTable1.getValueAt(row, 7);
                    String sql = "update buku set stok = '"+stok+"' + '"+banyak+"'"
                            + "where judul = '"+judul+"'";
                    pst = db.getConnection().prepareStatement(sql);
                    pst.execute();
                }
            }
            JOptionPane.showMessageDialog(null, "Berhasil dibatalkan");
            jTable1.setModel(model);
            loadtbl();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        try{
            db.koneksiDB();
            int rows = jTable1.getRowCount();
            PreparedStatement pst;
            pinjam p = new pinjam();
            
            for (int row = 0; row < rows; row++) 
            {
                String strib = jTable1.getValueAt(row, 0).toString();
                int id_buku = Integer.parseInt(strib);
                String strim = jTable1.getValueAt(row, 2).toString();
                int id_member = Integer.parseInt(strim);
                
                String tgs = (String)jTable1.getValueAt(row, 4);
                p.setStgl_selang(tgs);
                String selang = p.getStgl_selang();
                
                String tgp = (String)jTable1.getValueAt(row, 5);
                p.setStgl_kembali(tgp);
                String kembali = p.getStgl_kembali();
                
                String s = (String)jTable1.getValueAt(row, 6);
                
                String string = jTable1.getValueAt(row, 7).toString();
                int byk = Integer.parseInt(string);
                String strid = jTable1.getValueAt(row, 8).toString();
                int id_user = Integer.parseInt(strid);
                
                String kueri = "insert into peminjaman(id_buku, id_member, "
                    + "tgl_selang, tgl_kembali, status, banyak, id_user) values "
                    + "('"+id_buku+"','"+id_member+"','"+tgs+"','"+tgp+"','"+s+"','"+byk+"','"+id_user+"')";
                pst = db.getConnection().prepareStatement(kueri);   
                pst.execute();
            }
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            jTable1.setModel(model);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        db.koneksiDB();
        member m = new member();
        m.setNamaMember(nama.getText());
        String cari = m.getNamaMember();
        try{
            String sql = "select * from member where nama like '%"+cari+"%'";
            PreparedStatement pst = db.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
//                JOptionPane.showMessageDialog(null, "ketemu");
                idmember.setText(rs.getString(1));
                namamember.setText(rs.getString(3));
            }
            else{
                JOptionPane.showMessageDialog(null, m.STATUS()+ "Tidak ditemukan");
            }
        }
        catch(Exception e ){
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        db.koneksiDB();
        buku b = new buku();
        b.setId_buku(Integer.parseInt(kode.getText()));
        int id_buku = b.getId_buku();
        try{
            String sql = "select * from buku where id_buku = ?";
            PreparedStatement pst = db.getConnection().prepareStatement(sql);
            pst.setInt(1, id_buku);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
//                JOptionPane.showMessageDialog(null, "Data ditemukan");
                judul.setText(rs.getString(2));
                pengarang.setText(rs.getString(3));
                jumlahhalaman.setText(rs.getString(4));
                penerbit.setText(rs.getString(5));
                tahunterbit.setText(rs.getString(6));
                stok.setText(rs.getString(7));
                lokasirak.setText(rs.getString(8));
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                kode.setText("");
            }
        }
        catch(Exception e){
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarpeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField banyak;
    private javax.swing.JTextField idmember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField jumlahhalaman;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField lokasirak;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namamember;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField pengarang;
    private javax.swing.JTextField stok;
    private javax.swing.JTextField tahunterbit;
    private javax.swing.JTextField tglkembali;
    private javax.swing.JTextField tglpinjam;
    // End of variables declaration//GEN-END:variables
}
