/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prepus;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class daftarmember extends javax.swing.JFrame {
    /**
     * Creates new form daftarmember
     */
    private Connection koneksi;
    private koneksi db = new koneksi();
    public daftarmember() {
        initComponents();
        jLabel1.setText(main.getnama());
        loadtbl();
        jLabel1.setVisible(false);
    }
    private void loadtbl(){
        db.koneksiDB();
        DefaultTableModel model  = new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No.Telp");
        try{
            String tabel = "select * from member";
            PreparedStatement tbl = db.getConnection().prepareStatement(tabel);
            ResultSet rss = tbl.executeQuery();
            while(rss.next()){
                model.addRow(new Object[]{rss.getString(2), rss.getString(3), rss.getString(4), rss.getString(5), rss.getString(6)});
            }
            jTable1.setModel(model);
        }
        catch(Exception e ){

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alamat = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        tilpun = new javax.swing.JTextField();
        NIK = new javax.swing.JTextField();
        L = new javax.swing.JRadioButton();
        P = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alamat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alamat.setText("alamat");
        alamat.setBorder(null);
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 313, 190, 35));

        nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama.setText("nama");
        nama.setBorder(null);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 190, 35));

        tilpun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tilpun.setText("nomor tilpun");
        tilpun.setBorder(null);
        getContentPane().add(tilpun, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 30));

        NIK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NIK.setText("nik");
        NIK.setBorder(null);
        NIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIKActionPerformed(evt);
            }
        });
        getContentPane().add(NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, 30));

        L.setText("Laki-Laki");
        getContentPane().add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        P.setText("Perempuan");
        getContentPane().add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 930, 410));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 290, -1));

        cari.setText("Masukkan Nama");
        cari.setBorder(null);
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, 160, 30));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 30, 50, 50));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 30, 50));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 40, 40));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tambah member.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIKActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        db.koneksiDB();
        String pekor = cari.getText();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No.Telp");
        try{
            String sql = "select * from member where nama like '%"+pekor+"%'";
            PreparedStatement pst = db.getConnection().prepareStatement(sql);
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                model.addRow(new Object[]
                {
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                }
                );
            }
            jTable1.setModel(model);
        }
        catch(Exception e){
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        member m = new member();
        m.setMNIK(NIK.getText());
        String nik = m.getMNIK();
        m.setNamaMember(nama.getText());
        String namamember = m.getNamaMember();
        m.setAlamatMember(alamat.getText());
        String alamat = m.getAlamatMember();
        if (L.isSelected()) {
            m.setJenis_kelamin("Laki-laki");
        }
        else if (P.isSelected()){
            m.setJenis_kelamin("Perempuan");
        }
        String jenis_kelamin = m.getJenis_kelamin();
        m.setTilpunMember(tilpun.getText());
        String tilpun = m.getTilpunMember();
        
        try{
            db.koneksiDB();
            String sql = "insert into member(m_nik, nama, alamat, kelamin, no_tilpun)"
                    + "values (?,?,?,?,?)";
            PreparedStatement pst = db.getConnection().prepareStatement(sql);
            pst.setString(1, nik);
            pst.setString(2, namamember);
            pst.setString(3, alamat);
            pst.setString(4, jenis_kelamin);
            pst.setString(5, tilpun);
            int rs = pst.executeUpdate();
            
            if (rs == 1) {
                m.STATUS();
                JOptionPane.showMessageDialog(null, "Data Member berhasil ditambahkan!...");
                DefaultTableModel model  = new DefaultTableModel();
                model.addColumn("NIK");
                model.addColumn("Nama");
                model.addColumn("Alamat");
                model.addColumn("Jenis Kelamin");
                model.addColumn("No.Telp");
                try{
                    String tabel = "select * from member";
                    PreparedStatement tbl = db.getConnection().prepareStatement(tabel);
                    ResultSet rss = tbl.executeQuery();
                    while(rss.next()){
                        model.addRow(new Object[]{rss.getString(2), rss.getString(3), rss.getString(4), rss.getString(5), rss.getString(6)});
                    }
                    jTable1.setModel(model);
                }
                catch(Exception e ){

                }

            }
            else{
                System.out.println("Data Gagal ditambakan");
            }
            
        }
        catch(Exception e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        NIK.setText("");
        nama.setText("");
        alamat.setText("");
        tilpun.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarmember().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton L;
    private javax.swing.JTextField NIK;
    private javax.swing.JRadioButton P;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField tilpun;
    // End of variables declaration//GEN-END:variables
}
