/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prepus;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class daftarbuku extends javax.swing.JFrame {

    /**
     * Creates new form daftarbuku
     */
    private Connection koneksi;
    koneksi db = new koneksi();
    public daftarbuku() {
        initComponents();
        jLabel1.setText(main.getnama());
        loadtbl();
    }
    private void loadtbl(){
        db.koneksiDB();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Judul Buku");
        model.addColumn("Pengarang");
        model.addColumn("Jumlah Halaman");
        model.addColumn("Penerbit");
        model.addColumn("Tahun Terbit");
        model.addColumn("Stok");
        model.addColumn("Lokasi Rak Buku");
        String tabel = "Select * from buku";
        try{
            PreparedStatement pst = db.getConnection().prepareStatement(tabel);
            ResultSet tampil = pst.executeQuery();
            while(tampil.next()){
                model.addRow(new Object[]{tampil.getString(2),tampil.getString(3),
                tampil.getString(4),tampil.getString(5),tampil.getString(6),
                tampil.getString(7), tampil.getString(8)});
            }
            jTable2.setModel(model);
        }
        catch(Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        png = new javax.swing.JTextField();
        jh = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        pnb = new javax.swing.JTextField();
        tb = new javax.swing.JTextField();
        lb = new javax.swing.JTextField();
        jb = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        golek = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        png.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        png.setText("Pengarang");
        png.setBorder(null);
        getContentPane().add(png, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 190, 30));

        jh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jh.setText("Jumlah Halaman");
        jh.setBorder(null);
        getContentPane().add(jh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 190, 30));

        st.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        st.setText("Stok");
        st.setBorder(null);
        getContentPane().add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 190, 30));

        pnb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnb.setText("Penerbit");
        pnb.setBorder(null);
        getContentPane().add(pnb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 190, 40));

        tb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tb.setText("Tahun Terbit");
        tb.setBorder(null);
        getContentPane().add(tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 190, 30));

        lb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lb.setText("Lokasi buku");
        lb.setBorder(null);
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 30));

        jb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jb.setText("Judul Buku");
        jb.setBorder(null);
        getContentPane().add(jb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, 30));

        jTable2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 830, 400));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 740, 90, -1));

        golek.setText("Masukkan Judul buku");
        golek.setBorder(null);
        getContentPane().add(golek, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, 160, 30));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1294, 44, 40, 40));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 710, 50, 40));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 710, 50, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 710, 40, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Daftar Buku.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        db.koneksiDB();
        buku b = new buku();
        b.setJudulBuku(jb.getText());
        String judulbuku = b.getJudulBuku();
        b.setPengarang(png.getText());
        String pengarang = b.getPengarang();
        b.setJumhal(Integer.parseInt(jh.getText()));
        int jumhal = b.getJumhal();
        b.setPenerbit(pnb.getText());
        String penerbit = b.getPenerbit();
        b.setTabit(Integer.parseInt(tb.getText()));
        int tabit = b.getTabit();
        b.setStok(Integer.parseInt(st.getText()));
        int stok = b.getStok();
        b.setLokasiBuku(lb.getText());
        String lokasibuku = b.getLokasiBuku();
        
        try{
            String sql = "insert into buku(judul, pengarang, jumhal, penerbit, tabit,stok, lokasi)"
                    + "values(?,?,?,?,?,?,?)";
            PreparedStatement pst = db.getConnection().prepareStatement(sql);
            pst.setString(1, judulbuku);
            pst.setString(2, pengarang);
            pst.setInt(3, jumhal);
            pst.setString(4, penerbit);
            pst.setInt(5, tabit);
            pst.setInt(6, stok);
            pst.setString(7, lokasibuku);
            int rs = pst.executeUpdate();
            
            if(rs == 1){
                JOptionPane.showMessageDialog(null, "Data buku berhasil ditambahkan!!!");
                System.out.println("Data buku berhasil ditambahkan");
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("Judul Buku");
                model.addColumn("Pengarang");
                model.addColumn("Jumlah Halaman");
                model.addColumn("Penerbit");
                model.addColumn("Tahun Terbit");
                model.addColumn("Stok");
                model.addColumn("Lokasi Rak Buku");
                String tabel = "Select * from buku";
                try{
                    PreparedStatement tambah = db.getConnection().prepareStatement(tabel);
                    ResultSet tampil = tambah.executeQuery();
                    while(tampil.next()){
                        model.addRow(new Object[]{tampil.getString(2),tampil.getString(3),
                        tampil.getString(4),tampil.getString(5),tampil.getString(6),
                        tampil.getString(7), tampil.getString(8)});
                    }
                    jTable2.setModel(model);
                }
                catch(Exception e){

                }

                
            }
            else{
                
            }
        }
        catch(Exception e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jb.setText("");
        jh.setText("");
        lb.setText("");
        pnb.setText("");
        png.setText("");
        st.setText("");
        tb.setText("");
        golek.setText("");
        loadtbl();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new menu().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        db.koneksiDB();
        String cari = golek.getText();
        try{
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Judul Buku");
            model.addColumn("Pengarang");
            model.addColumn("Jumlah Halaman");
            model.addColumn("Penerbit");
            model.addColumn("Tahun Terbit");
            model.addColumn("Stok");
            model.addColumn("Lokasi Rak Buku");
            String search = "select * from buku where judul like '%"+cari+"%'";
            PreparedStatement pst = db.getConnection().prepareStatement(search);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
//                JOptionPane.showMessageDialog(null, "Data ditemukan!");
                model.addRow(new Object[]{rs.getString(2),rs.getString(3),
                rs.getString(4),rs.getString(5),
                rs.getString(6),rs.getString(7),
                rs.getString(8)});
            }
            jTable2.setModel(model);
        }
        catch(Exception e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarbuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField golek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jb;
    private javax.swing.JTextField jh;
    private javax.swing.JTextField lb;
    private javax.swing.JTextField pnb;
    private javax.swing.JTextField png;
    private javax.swing.JTextField st;
    private javax.swing.JTextField tb;
    // End of variables declaration//GEN-END:variables
}
