/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prepus;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class daftarpengembalian extends javax.swing.JFrame {

    /**
     * Creates new form daftarpengembalian
     */
    private Connection koneksi;
    koneksi db = new koneksi();
    public daftarpengembalian() {
        initComponents();
        jLabel1.setText("Operator : "+main.getnama());
        jLabel2.setText("USER ID : "+main.getid_user());
        stok.setVisible(false);
        loadtbl();
    }
    private void loadtbl(){
        db.koneksiDB();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pengembalian");
        model.addColumn("Judul");
        model.addColumn("Nama Member");
        model.addColumn("Tanggal Dipinjam");
        model.addColumn("Tanggal Kembali");
        model.addColumn("Dikembalikan");
        model.addColumn("Status");
        model.addColumn("Banyak Buku yang dipinjam");
        model.addColumn("Operator");
        try{
            String sql = "SELECT p.id_pengembalian, b.judul, m.nama, p.tgl_selang, p.tgl_balik, p.kembali, p.status, p.banyak, u.nama "
                    + "FROM buku b, member m, pengembalian p, user u "
                    + "WHERE m.id_member = p.id_member AND u.id_user = p.id_user "
                    + "AND b.id_buku = p.id_buku";
            PreparedStatement pst = db.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]
                    {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9)
                });
                
            }
            jTable1.setModel(model);
        }
        
        catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idpinjam = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jb = new javax.swing.JTextField();
        pm = new javax.swing.JTextField();
        tgd = new javax.swing.JTextField();
        tgk = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        op = new javax.swing.JTextField();
        kembalipada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kb = new javax.swing.JTextField();
        im = new javax.swing.JTextField();
        cari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ido = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idpinjam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idpinjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(idpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 216, 200, 30));

        b.setEditable(false);
        b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b.setText("Banyak");
        b.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 404, 245, 35));

        jb.setEditable(false);
        jb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jb.setText("Judul");
        jb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 245, 35));

        pm.setEditable(false);
        pm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pm.setText("Peminjam");
        pm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 240, 35));

        tgd.setEditable(false);
        tgd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tgd.setText("Tanggal Dipinjam");
        tgd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tgd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 245, 35));

        tgk.setEditable(false);
        tgk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tgk.setText("Tanggal Kembali");
        tgk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tgk, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 306, 240, 35));

        s.setEditable(false);
        s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s.setText("Status");
        s.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 349, 240, 36));

        op.setEditable(false);
        op.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        op.setText("Operator");
        op.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(op, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 240, 35));

        kembalipada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kembalipada.setText("YYYYMMDD");
        kembalipada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(kembalipada, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 245, 35));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 740, 330));

        kb.setEditable(false);
        kb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kb.setText("Kode Buku");
        kb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbActionPerformed(evt);
            }
        });
        getContentPane().add(kb, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 261, 245, 35));

        im.setEditable(false);
        im.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        im.setText("Id Member");
        im.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        im.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imActionPerformed(evt);
            }
        });
        getContentPane().add(im, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 240, 35));

        cari.setText("Cari ID Pengembalian");
        cari.setBorder(null);
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 260, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 150, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 150, -1));

        ido.setEditable(false);
        ido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ido.setText("ID Operator");
        ido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 245, 35));

        stok.setEditable(false);
        stok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stok.setText("stok");
        stok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 240, 35));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 80, 60, 40));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 50, 30));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 210, 100, 80));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 300, 170, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pengembalian.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        db.koneksiDB();
        String pekopeko = cari.getText();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pengembalian");
        model.addColumn("Judul");
        model.addColumn("Nama Member");
        model.addColumn("Tanggal Dipinjam");
        model.addColumn("Tanggal Kembali");
        model.addColumn("Dikembalikan");
        model.addColumn("Status");
        model.addColumn("Banyak Buku yang dipinjam");
        model.addColumn("Operator");
        try{
            String sql = "SELECT p.id_pengembalian, b.judul, m.nama, p.tgl_selang, p.tgl_balik, p.kembali, p.status, p.banyak, u.nama "
                    + "FROM buku b, member m, pengembalian p, user u "
                    + "WHERE m.id_member = p.id_member AND u.id_user = p.id_user "
                    + "AND b.id_buku = p.id_buku "
                    + "AND id_pengembalian like '%"+pekopeko+"%'";
            PreparedStatement pst = db.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]
                    {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9)
                });
                
            }
            jTable1.setModel(model);
        }
        
        catch(Exception e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void imActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        db.koneksiDB();
        String cari = idpinjam.getText();        
        try{
            String sql = "SELECT b.id_buku, p.id_peminjaman, m.id_member, u.id_user,"
                    + " b.judul, m.nama, p.tgl_selang, "
                    + "p.tgl_kembali, p.status, p.banyak, u.nama, b.stok "
                    + "FROM buku b, member m, peminjaman p, user u "
                    + "WHERE m.id_member = p.id_member AND u.id_user = p.id_user "
                    + "AND b.id_buku = p.id_buku "
                    + "AND p.id_peminjaman = '"+cari+"'";
            PreparedStatement pst = db.getConnection().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                kb.setText(rs.getString(1));
                im.setText(rs.getString(3));
                ido.setText(rs.getString(4));
                jb.setText(rs.getString(5));
                pm.setText(rs.getString(6));
                tgd.setText(rs.getString(7));
                tgk.setText(rs.getString(8));
                s.setText(rs.getString(9));
                b.setText(rs.getString(10));
                op.setText(rs.getString(11));
                stok.setText(rs.getString(12));
           }
            else{
                JOptionPane.showMessageDialog(null, "Data tidak dditemukan");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void kbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        pinjam p = new pinjam();
        
        p.setStgl_selang(tgd.getText());
        String selang = p.getStgl_selang();
        p.setStgl_kembali(tgk.getText());
        String mbalek = p.getStgl_kembali();
        
        int kembali = Integer.parseInt(tgk.getText());
        int dikembalikan = Integer.parseInt(kembalipada.getText());
        String status = "Sudah dikembalikan";
        String tidaktepatwaktu = "Dikembalikan tidak tepat waktu, didenda Rp.500 per hari";
        String tepatwaktu = "Dikembalikan tepat waktu";
        
        if (dikembalikan > kembali) {
                String simpan = "insert into pengembalian(id_buku, id_member, tgl_selang, "
                        + "tgl_balik, kembali, status, banyak, id_user)"
                        + "values ('"+kb.getText()+"','"+im.getText()+"',"
                        + "'"+tgd.getText()+"','"+tgk.getText()+"',"
                        + "'"+kembalipada.getText()+"','"+tidaktepatwaktu+"',"
                        + "'"+b.getText()+"','"+ido.getText()+"')";
                    try {

                        PreparedStatement pengembalian = db.getConnection().prepareStatement(simpan);
                        pengembalian.executeUpdate();
                    }
                    catch (Exception e){
                    }
        }
        else{
                String simpan = "insert into pengembalian(id_buku, id_member, tgl_selang, "
                        + "tgl_balik, kembali, status, banyak, id_user)"
                        + "values ('"+kb.getText()+"','"+im.getText()+"',"
                        + "'"+tgd.getText()+"','"+tgk.getText()+"',"
                        + "'"+kembalipada.getText()+"','"+tepatwaktu+"',"
                        + "'"+b.getText()+"','"+ido.getText()+"')";
                    try {

                        PreparedStatement pengembalian = db.getConnection().prepareStatement(simpan);
                        pengembalian.executeUpdate();
                    }
                    catch (Exception e){
                    }
            
        }
        String upbuku = "update buku set stok = '"+stok.getText()+"' + '"+b.getText()+"' "
                + "where judul = '"+jb.getText()+"'";
        
        try {
            
            PreparedStatement upb = db.getConnection().prepareStatement(upbuku);
            upb.executeUpdate();
            
        } catch (SQLException ex) {

        }
            JOptionPane.showMessageDialog(null, "Data sudah ditambahkan!");
            String sql = "UPDATE peminjaman SET STATUS = '"+status+"' "
                    + "WHERE id_peminjaman = '"+idpinjam.getText()+"'";
            try{
                PreparedStatement pst = db.getConnection().prepareStatement(sql);
                pst.executeUpdate();
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
            loadtbl();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarpengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField ido;
    private javax.swing.JTextField idpinjam;
    private javax.swing.JTextField im;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jb;
    private javax.swing.JTextField kb;
    private javax.swing.JTextField kembalipada;
    private javax.swing.JTextField op;
    private javax.swing.JTextField pm;
    private javax.swing.JTextField s;
    private javax.swing.JTextField stok;
    private javax.swing.JTextField tgd;
    private javax.swing.JTextField tgk;
    // End of variables declaration//GEN-END:variables
}
